import { Montserrat } from "next/font/google";
import "./globals.css";
import favicon from "@/app/favicon.ico";
import Header from "@/app/components/Header";
import { ThemeProvider } from "@/app/components/ThemeProvider";
import Footer from "@/app/components/Footer";
import LeftSidebar from "@/app/components/LeftSidebar";

const font = Montserrat({ subsets: ["latin"] });

export const metadata = {
    title: "rODE Solver",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <link rel="shortcut icon" href={favicon.src} type="image/x-icon" />
            <body className={font.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange>
                    <Header />
                    <div className="flex flex-row">
                        <LeftSidebar />
                        {children}
                    </div>
                    <Footer />
                </ThemeProvider>
            </body>
        </html>
    );
}
