import { Montserrat } from "next/font/google";
import "./globals.css";
import favicon from "./favicon.ico";
import Header from "./components/Header";
import { ThemeProvider } from "./components/ThemeProvider";
import Footer from "./components/Footer";

const font = Montserrat({ subsets: ["latin"] });

export const metadata = {
    title: "rODE Solver",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <link rel="shortcut icon" href={favicon.src} type="image/x-icon" />
            <body className={font.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange>
                    <Header />
                    {children}
                    <Footer />
                </ThemeProvider>
            </body>
        </html>
    );
}
