import { Montserrat } from "next/font/google";
import "./globals.css";
import favicon from "./favicon.ico";

const font = Montserrat({ subsets: ["latin"] });

export const metadata = {
    title: "rODE Solver",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <link rel="shortcut icon" href={favicon.src} type="image/x-icon" />
            <body className={font.className}>{children}</body>
        </html>
    );
}
